#!/usr/bin/env bash
# script to print info about hostname and
# its subdomains
subdomains=("www" "lb-01" "web-01" "web-02")

function domain_info() {
	line=$(dig "$1.$2" | grep -A1 'ANSWER SECTION' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "$1 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]; then
	for domain in "${subdomains[@]}"; do domain_info "$domain" "$1"; done;
elif [ "$#" == 2 ]; then
	domain_info "$2" "$1"
fi
