#!/usr/bin/env bash
# This script will move file from client to server using scp

if [[ "$#" -lt 3 ]]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
	exit;
fi;

scp "$1" "$3"@"$2":~/ -i "$4";
