#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page)
# using curl, it must return a page that contains the string Hello World!
sudo apt-get update -y -qq && \
	sudo apt-get install nginx -y;
sudo service nginx start;
sudo ufw allow 'Nginx HTTP';
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html;
sudo service nginx restart;
