#!/usr/bin/env bash
# install nginx on the server
# allow the nginx http to be used

sudo apt update -y -qq && \
	sudo apt-get install nginx -y;

sudo service nginx start;

sudo ufm allow 'Nginx HTTP';

sudo chown -R "$USER":"$USER" /var/www/;
sudo chmod -R 755 /var/www/;

sed -i 's/server_name _;/server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}/' /etc/nginx/sites-enabled/default;

echo "Hello World!" | dd status=none of='/var/www/html/index.nginx-debian.html';

sudo service nginx restart;
