#!/usr/bin/env bash
# Create Server with header inserted into it

function install () {
	command -v "$1" &> /dev/null
	if [[ $? -ne 0 ]]; then
		sudo apt-get update -y -qq && \
		sudo apt-get install nginx -y
	fi
}

install nginx

sudo ufw allow 'Nginx HTTP'

if [[ -d /var/www ]]; then
	sudo chown -R "$USER":"$USER" /var/www
	sudo chmod -R 755 /var/www
else
	sudo mkdir /var/www/
	sudo chown -R "$USER":"$USER" /var/www
	sudo chmod -R 755 /var/www
fi

for dir in /var/www/{html,error}; do
	if ! [[ -d "$dir" ]]; then 
		sudo mkdir -p "$dir"
	fi
done;

echo -e "Hello World!" > /var/www/html/index.html

echo -e "Ceci n'est pas une page" > /var/www/html/error_404.html;

service_con=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	server_name _;

	add_header X-Served-By \$hostname;
	
	location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files \$uri \$uri/ =404;
        }

	rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;

	error_page 404 /error_404.html;

	location = /error_404.html {
		internal;
	}
}"

echo "$service_con" | sudo dd status=none of='/etc/nginx/sites-enabled/default'

sudo service nginx restart;