#!/usr/bin/env bash
# automation script for building load balancer 
# using HAProxy with roundrobin algorithm

function install() {
	command -v "$1" &> /dev/null;

	if [[ $? -ne 0 ]]; then
		sudo apt-get update
		sudo apt-get -y install --no-install-recommends software-properties-common;
		sudo add-apt-repository -y ppa:vbernat/haproxy-2.4;
		sudo apt-get -y install haproxy;
	fi
}

install haproxy

proxy_config="\
frontend ammar_frontend
	bind *:80
	mode http
	default_backend ammar_backend

backend ammar_backend
	balance roundrobin
	server 121379-web-01 52.91.153.115:80 check
	server 121379-web-02 52.91.202.178:80 check
"

[ -f "/etc/default/haproxy" ] || touch "/etc/default/haproxy"
[ -f "/etc/haproxy/haproxy.cfg" ] || touch "/etc/haproxy/haproxy.cfg"

echo "$proxy_config" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi;
