#!/usr/bin/env bash
# script to tell a story about shell users
file=/etc/passwd
while IFS= read -r line;
do
	name=$(echo "$line" | cut -d ":" -f 1)
	passcode=$(echo "$line" | cut -d ":" -f 2)
	uid=$(echo "$line" | cut -d ":" -f 3)
	gang=$(echo "$line" | cut -d ":" -f 4)
	userinfo=$(echo "$line" | cut -d ":" -f 5)
	dir=$(echo "$line" | cut -d ":" -f 6)
	rootdir=$(echo "$line" | cut -d ":" -f 7)
	echo "The user $name is part of the $gang gang, lives in $dir and rides $rootdir. $uid's place is protected by the passcode $passcode, more info about the user here: $userinfo"
done < "$file";