#!/usr/bin/env bash
# Script to configure firewall using ufw
sudo apt-get install ufw
sudo sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
sudo ufw disable
sudo ufw allow outgoing
sudo ufw deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo service ufw restart
sudo ufw enable
