#!/usr/bin/env bash
# give all rights to user nginx and make him
# the only one who can edit nginx configuration
sudo sed -i 's/80 default_server/8080 default_server/' \
	/etc/nginx/sites-available/default

chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
service nginx reload
service nginx restart
