#!/usr/bin/env bash
# same as task 1 but in 7 lines only
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
